services:
  app:
    restart: always
    image: whatwewant/connect-doreamon:v1
    platform: linux/amd64
    ports:
      - 0.0.0.0:8080:8080 # webhook
    environment:
      DEBUG: ${DEBUG}
      SESSION_KEY: ${SESSION_KEY}
      #
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      # #
      # UPSTREAM: ${UPSTREAM}
      #
      FRONTEND: ${FRONTEND}
      BACKEND: ${BACKEND}

